### ISSUE TITLE
Crash when _FieldBased is not set to 0

### ISSUE THREAD

**Issue by Reel-Deal** [Asd-g/AviSynthPlus-w2xncnnvk#1]
Hi Asd,

I encountered an odd problem. w2xncnnvk (I think) seems to crash when _FieldBased is set to 2 or 1. 

```
ColorBars(pixel_type="YUV420P8")
propSet("_FieldBased", 2)
z_ConvertFormat(pixel_type="RGBPS", interlaced=false)
w2xncnnvk()
ConvertBits(8)
```

If I comment out w2xncnnvk() then z_ConvertFormat correctly errors out with "clip must be frame-based". Also if I set  interlaced=true it works correctly. I'm not 100% if w2xncnnvk is to blame here but if it's a problem with avsresize or avs+ itself then I'll report it in the appropriate place.

The error I get in VDub2:

>An out-of-bounds memory access (access violation) occurred in module 'VirtualDub64'...
...reading address 0000000000000040.

I only discovered this bug because TFM does not set _FieldBased to 0 after field matching.

**Comment by Asd-g** [comment]
Hi,

Thanks for the report. First avs+ have to be fixed (https://github.com/AviSynth/AviSynthPlus/pull/299) then I will update all my c_api plugins because all of them have the same behavior.

**Comment by Reel-Deal** [comment]
Thanks for taking a look at the issue. I'll leave the issue open for now.

**Comment by Asd-g** [comment]
1.0.1 should be fine with avs+ [r3689](https://gitlab.com/uvz/AviSynthPlus-Builds).

**Comment by Reel-Deal** [comment]
Thanks for the update, I can confirm that it now works without a crash.
