### ISSUE TITLE
Request: port realcugan-ncnn-vulkan

### ISSUE THREAD

**Issue by tormento** [Asd-g/AviSynthPlus-w2xncnnvk#2]
Would you please port [realcugan-ncnn-vulkan](https://github.com/nihui/realcugan-ncnn-vulkan)?

That would be great!

**Comment by Asd-g** [comment]
[mlrt](https://github.com/AmusementClub/vs-mlrt) is in my list.

**Comment by tormento** [comment]
Oh, wow. It would be really nice to have it, mostly for cuda support.

**Comment by Asd-g** [comment]
https://github.com/Asd-g/avs-mlrt
