### ISSUE TITLE
Support for single channel Y32 format?

### ISSUE THREAD

**Issue by Reel-Deal** [Asd-g/AviSynthPlus-w2xncnnvk#3]
Hi asd,

I was wondering if adding support for Y32 grayscale is possible? By possible meaning, not a lot of work on your end. I was trying out the denoise only feature of w2xncnnvk and noticed that it does a very good job in removing halo, ringing and mosquito noise in animation. I placed w2xncnnvk in one of the dehalo scripts that has masking etc, and was pleased with the result. The only downside is that it is slow. Since almost all dehalo scripts work on luma only, it would be beneficial if w2xncnnvk accepted Y32.

I'm not sure how things work internally, if the models need RGB to work, but if it's something not complicated, would you consider adding support? Even a planes parameter would work, if that makes it easier for you.

If it's too time consuming, feel free to tell me no :) 

Edit: changed "formats" to Y32

**Comment by Asd-g** [comment]
Hi,

With the these models (they are for RGB) wouldn't be possible.

**Comment by Reel-Deal** [comment]
I feared that would be the case. Thanks for the confirmation.
